### PR TITLE
add delete expense feature and fix all issues from pe-d

### LINKED ISSUE #112: [PE-D][Tester B] Requires proper description when output is given
When a person pays on behalf of a group, let us say 3 people including him, the command says that the person who paid owes a particular amount when spltting equally. Instead, the output could be phrased as the person who paid "his name bears AMOUNT", whereby the amount is his share of the total expense.

When I am listing expenses for the group, the output does not specify who owes who and also prints the payer name as he owes a particular amount, when he is the one who paid for a particular transaction.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Praneet-25/ped#1

### LINKED ISSUE #115: [PE-D][Tester D] Expense with unequal distribution does not work at all
The expense /unequal /amount feature does not work. When entering the username with the amount owed, it registers the amount owed as part of the user name, resulting in an error message stating that for example (nigel 20 is not a member of the group). When removing the amount owed, it also does not run as amount due for the user is empty.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: nigelheng/ped#5

### LINKED ISSUE #118: [PE-D][Tester A] Unable to spilt expense unequally
it was state that to spilt expenses unequally:
`Format: expense DESCRIPITON /unequal /amount TOTAL_AMOUNT /paid PAYER_USER_NAME /user
USER_NAME AMOUNT_OWED /user USER_NAME AMOUNT_OWED` 

However, when I typed in:
`expense present /unequal /amount 40000 /paid alice /user ben 500 /user carol 1000 /user den 500`

there is an error message when I have already added the members to the group:
` ben 500 is not a member of the group!`

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: LuoYu-uwu/ped#2

### LINKED ISSUE #125: [PE-D][Tester E] Inaccurate print return for expense
Inaccurate print return. `Alice` does not owe `Alice` money.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: syj02/ped#6

### LINKED ISSUE #130: [PE-D][Tester E] `0` is a valid input for expense input
-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: syj02/ped#8

### LINKED ISSUE #131: [PE-D][Tester C] Special characters inside expense description causes error when loading file.
Using commas in expense description causes errors when reading the group file. Hence, the file cannot be loaded again.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: chenhowy/ped#9

### LINKED ISSUE #133: [PE-D][Tester E] Negative amount is valid for expense paid
-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: syj02/ped#9

### LINKED ISSUE #134: [PE-D][Tester B] Create expense split unequally not working as intended
When I create an expense which is to be split unequally, the first user who owes the payer money is said to be not in the group. However, when i type in the command balance followed by his name, it says he owes a certain amount of money  showing that he is the group. This proves to be a major bug.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: Praneet-25/ped#3

### LINKED ISSUE #135: [PE-D][Tester E] Error during unequal split of expense
read `Bob 5` as member name when, according to the UG, `Bob` is member name and `5` is amount owed.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: syj02/ped#10

### LINKED ISSUE #137: [PE-D][Tester D] Expense that cannot be split equally lists as a very long decimal
When splitting amounts that cannot be split equally, the app returns a very long decimal value when listing the amount settled by each member.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: nigelheng/ped#11

### LINKED ISSUE #139: [PE-D][Tester E] Input with character after number is a valid amount for expense
-------------
Labels: `type.FunctionalityBug` `severity.High`
original: syj02/ped#11

### PR DESCRIPTION
**Pull request by mukund1403**
close #139 
close #137 
close #135 
close #134 
close #133 
close #131 
close #130 
close #125 
close #118 
close #115 
close #112

### CODE REVIEW

File: src/main/java/seedu/duke/Parser.java [hunk 1]
```diff
@@ -142,7 +142,24 @@ public void handleUserInput() throws EndProgramException, ExpensesException {
             GroupCommand.createGroup(argument);
             break;
         case "delete":
-            GroupCommand.deleteGroup(argument);
+            String[] deleteTypeAndValue = argument.split(" ");
```
Comment (MonkeScripts) [inline src/main/java/seedu/duke/Parser.java:145]: Good implementation of delete
